scrape_configs:
  - job_name: 'prometheus'

    scrape_interval: 5s

    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'grafana'

    scrape_interval: 5s

    static_configs:
      - targets: ['grafana:3000']

  - job_name: 'pushgateway'

    scrape_interval: 5s

    honor_labels: true

    static_configs:
      - targets: ['pushgateway:9091']

  - job_name: 'zipkin'

    scrape_interval: 5s

    metrics_path: '/prometheus'

    static_configs:
      - targets: ['zipkin:9411']

    metric_relabel_configs:
      - source_labels: [__name__]
        regex: '^status_(\d+)_(.*)$'
        replacement: '${1}'
        target_label: status
      - source_labels: [__name__]
        regex: '^status_(\d+)_(.*)$'
        replacement: '${2}'
        target_label: path
      - source_labels: [__name__]
        regex: '^status_(\d+)_(.*)$'
        replacement: 'http_requests_total'
        target_label: __name__
      - source_labels: [__name__]
        regex: '^response_(.*)$'
        replacement: '${1}'
        target_label: path
      - source_labels: [__name__]
        regex: '^response_(.*)$'
        replacement: 'http_request_duration_milliseconds'
        target_label: __name__

  - job_name: 'elasticsearch'

    scrape_interval: 30s

    scrape_timeout:  5s

    metrics_path: "/metrics"

    static_configs:
      - targets: ['es_exporter:9108']

