{
 "title": "Zipkin Metrics",
 "description": "Visualize Prometheus metrics exported by OpenZipkin (http://zipkin.io/).",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "instances",
    "label": "Zipkin instances",
    "query": "label_values(http_server_requests_seconds_bucket, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Messages and spans received per transport",
   "type": "graph",
   "description": "Messages on left axis, Spans on right axis",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "messages per second" }
   ],
   "targets": [
    {
     "expr": "rate(zipkin_collector_messages_total{instance=~\"$instances\"}[1m])\n",
     "legendFormat": "{{instance}} {{transport}} messages"
    },
    {
     "expr": "rate(zipkin_collector_messages_dropped_total{instance=~\"$instances\"}[1m])\n",
     "legendFormat": "{{instance}} {{transport}} dropped messages"
    },
    {
     "expr": "rate(zipkin_collector_spans_total{instance=~\"$instances\"}[1m])\n",
     "legendFormat": "{{instance}} {{transport}} spans"
    },
    {
     "expr": "rate(zipkin_collector_spans_dropped_total{instance=~\"$instances\"}[1m])\n",
     "legendFormat": "{{instance}} {{transport}} dropped spans"
    }
   ]
  },
  {
   "title": "Bytes received per transport",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "decbytes", "label": "per second" }
   ],
   "targets": [
    {
     "expr": "rate(zipkin_collector_bytes_total{instance=~\"$instances\"}[1m])",
     "legendFormat": "{{instance}} {{transport}}"
    }
   ]
  },
  {
   "title": "Requests per second",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_count{job=\"zipkin\",instance=~\"$instances\"}[1m])",
     "legendFormat": "{{instance}} {{status}} {{uri}}"
    }
   ]
  },
  {
   "title": "Mean response times",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_sum{job=\"zipkin\",instance=~\"$instances\"}[1m])\n/\nrate(http_server_requests_seconds_count{job=\"zipkin\",instance=~\"$instances\"}[1m])",
     "legendFormat": "{{method}} {{instance}} {{uri}}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 14 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "uptime{instance=~\"$instances\"}"
    }
   ]
  },
  {
   "title": "Instance Uptime",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 14 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "expr": "process_uptime_seconds{instance=~\"$instances\"}"
    }
   ]
  },
  {
   "title": "90th percentile response time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum(rate(http_server_requests_seconds_bucket[1m])) by (uri, method, instance, le))",
     "legendFormat": "{{method}} {{instance}} {{uri}}"
    }
   ]
  },
  {
   "title": "HTTP Sessions",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "httpsessions_active{instance=~\"$instances\"}",
     "legendFormat": "{{instance}} active"
    },
    {
     "expr": "httpsessions_max{instance=~\"$instances\"}",
     "legendFormat": "{{instance}} max"
    }
   ]
  },
  {
   "title": "System CPUs used, Load",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "system_cpu_count{instance=~\"$instances\"}",
     "legendFormat": "{{instance}} CPUs"
    },
    {
     "expr": "system_load_average_1m{instance=~\"$instances\"}",
     "legendFormat": "{{instance}} load"
    }
   ]
  },
  {
   "title": "JVM Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{instance=~\"$instances\"}",
     "legendFormat": "{{instance}} {{area}} used"
    },
    {
     "expr": "jvm_memory_max_bytes{instance=~\"$instances\"}",
     "legendFormat": "{{instance}} {{area}} max"
    },
    {
     "expr": "jvm_buffer_total_capacity_bytes{instance=~\"$instances\"}",
     "legendFormat": "{{instance}} {{pool}} max"
    }
   ]
  },
  {
   "title": "Garbage Collection",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "short", "label": "count" }
   ],
   "targets": [
    {
     "expr": "delta(jvm_gc_pause_seconds_sum{instance=~\"$instances\"}[1m])",
     "legendFormat": "{{instance}} {{gc}} duration"
    },
    {
     "expr": "delta(jvm_gc_pause_seconds_count{instance=~\"$instances\"}[1m])",
     "legendFormat": "{{instance}} {{gc}} count"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_threads_current{instance=~\"$instances\"}",
     "legendFormat": "{{instance}} current"
    },
    {
     "expr": "jvm_threads_daemon{instance=~\"$instances\"}",
     "legendFormat": "{{instance}} daemon"
    },
    {
     "expr": "jvm_threads_peak{instance=~\"$instances\"}",
     "legendFormat": "{{instance}} peak"
    },
    {
     "expr": "jvm_threads_started_total{instance=~\"$instances\"}",
     "legendFormat": "{{instance}} started total"
    },
    {
     "expr": "jvm_threads_deadlocked{instance=~\"$instances\"}",
     "legendFormat": "{{instance}} deadlocked"
    },
    {
     "expr": "jvm_threads_deadlocked_monitor{instance=~\"$instances\"}",
     "legendFormat": "{{instance}} deadlocked monitor"
    }
   ]
  },
  {
   "title": "JVM Classes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_classes_loaded{instance=~\"$instances\"}",
     "legendFormat": "{{instance}} current"
    },
    {
     "expr": "jvm_classes_unloaded_total{instance=~\"$instances\"}",
     "legendFormat": "{{instance}} unloaded since boot"
    }
   ]
  }
 ]
}